### ISSUE TITLE
Link to the example on the README file is broken.

### ISSUE THREAD

**Issue by arthurdenner** [aleclarson/vana#24]
Hi! :wave: 

Link to the [example on the README file](https://codesandbox.io/s/nnx8zxx03p) is broken.

**Comment by aleclarson** [comment]
D'oh! I was deleting all of my unused sandboxes, and of course I overlook this!

Thanks for the heads up 👍

**Comment by aleclarson** [comment]
Here are the new links:
- https://codesandbox.io/s/z33pzx31wp
- https://github.com/alloc/vana-sandbox
